#!/bin/bash

: <<docstring
	This is intended to install all the common software, libs, packages, modules...
	that I commonly use, on a fresh Ubuntu installation
docstring

# Chromium
sudo apt-get --assume-yes install chromium-browser

# Sublime text
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get --assume-yes update
sudo apt-get --assume-yes install sublime-text-installer

# Terminator
sudo apt-get --assume-yes terminator
# TODO – configure terminator programatically

# Git
sudo apt-get --assume-yes install git

# Nodejs
sudo apt-get --assume-yes install nodejs-legacy
# npm
sudo apt-get --assume-yes install npm
# update nodejs using n and make a symbolic link
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
# TODO - compute the VERSION here
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node 
sudo n latest

# bower
npm install bower

# grunt
npm install grunt
sudo npm install -g grunt-cli

# python3-dev
sudo apt-get --assume-yes install python3-dev
sudo apt-get --assume-yes install redis-server

# Postgresql
sudo apt-get --assume-yes install postgresql postgresql-contrib
sudo apt-get --assume-yes install python-psycopg2

sudo apt-get --assume-yes install libpq-dev
sudo apt-get --assume-yes install memcached

# for cairocffi
sudo apt-get --assume-yes install libffi-dev

sudo apt-get --assume-yes install libmemcached-dev

# pip installation and upgrade
sudo apt-get --assume-yes install python-pip
pip install --upgrade pip

# virtual env
pip install virtualenvwrapper

echo "export WORKON_HOME=~/Envs" >> ~/.bashrc
echo "source ~/.local/bin/virtualenvwrapper.sh" >> ~/.bashrc

# TODO - have these configs
			# - bashrc aliases and branch highlighting code
			# - sublime text user settings and user preferences
			# 

# curl
sudo apt-get --assume-yes install curl

# Install media codecs
curl ftp://ftp.videolan.org/pub/debian/videolan-apt.asc | sudo apt-key add -
echo "deb ftp://ftp.videolan.org/pub/debian/stable ./" | sudo tee /etc/apt/sources.list.d/libdvdcss.list
sudo apt-get --assume-yes update
# vlc and mplayer
sudo apt-get --assume-yes install vlc vlc-data vlc-plugin-pulse browser-plugin-vlc mplayer2
# restricted extras
sudo apt-get --assume-yes install ubuntu-restricted-extras
# full DVD support
sudo apt-get --assume-yes install libdvdcss2 libdvdnav4 libdvdread4
sudo /usr/share/doc/libdvdread4/install-css.sh
